apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sringboot-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Vishal-1705/devops-automation-manifest.git
    targetRevision: HEAD
    path: ./

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true