apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s
  namespace: flux-demo
  labels:
    app: spring-boot-k8s
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.devops-integration: semver:~1.0.0
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 3 # Number of replicas that will be created for this deployment
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: vishalbasani/devops-integration:36
          # imagePullPolicy: IfNotPresent
          ports:
          - name: spring-boot-k8s-port
            containerPort: 80 # The port that the container is running on in the cluster
        serviceAccountName: binding-connector
