apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: spring-boot-k8s-svc
  namespace: flux-demo
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80
  type: NodePort # type of the service.
